version: "4"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["/django_app/Docker/app.sh"]
    depends_on:
      - redis
